# Generated by Django 3.2 on 2022-04-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220406_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_shoesize',
        ),
    ]
